services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: drf-rbac-web:latest
    container_name: drf-rbac-web
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${DOCKER_PORT:-8000}:8000
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
      - ./logs:/app/logs
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsS http://localhost:8000/health/ || exit 1" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Enables access to local services