services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: drf-rbac-web:latest
    container_name: drf_rbac_web
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "8000"
    volumes:
      - static_data:/app/static
      - ./media:/app/media
      - ./logs:/app/logs
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsS http://localhost:8000/health/ || exit 1" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - drf-rbac-network
  nginx:
    build: ./nginx
    image: drf-rbac-nginx:latest
    container_name: drf_rbac_nginx
    ports:
      - "${DOCKER_PORT:-8000}:80"
    volumes:
      - static_data:/static
      - ./media:/media
    depends_on:
      - web
    restart: unless-stopped
    networks:
      - drf-rbac-network
  
volumes:
  static_data:

networks:
  drf-rbac-network:
    external: true