# Generated by Django 5.2.5 on 2025-08-27 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Organization',
            new_name='organization',
        ),
    ]
